syntax: scss
extends:
  - stylelint-config-recommended-scss # https://github.com/kristerkari/stylelint-config-recommended-scss/blob/master/index.js
  - stylelint-config-recess-order # https://github.com/stormwarning/stylelint-config-recess-order
plugins:
  - stylelint-order
rules:
  # order/order: # https://github.com/hudochenkov/stylelint-order/tree/master/rules/order
